<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-03-20 at 22:37:44.
 */
class number2Test extends PHPUnit_Framework_TestCase {

    /**
     * @var number2
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new number2;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Generated from @assert (1, 2) == 3.
     *
     * @covers number2::add
     */
    public function testAdd() {
        $this->assertEquals(
            3
            , $this->object->add(1, 2)
        );
    }
}
